# Generated by Django 4.2 on 2024-08-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_rating_comment_rating_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
