# Generated by Django 4.2 on 2024-08-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='content',
        ),
    ]
